language: node_js
node_js: node
install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
cache:
  directories:
  - node_modules
script: npm build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.cadetcleanersdallas.com
  skip_cleanup: true
  acl: public_read
  local_dir: dist
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master,stage'