language: node_js
node_js: node
cache:
  directories:
  - node_modules
script: npm build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.cadetcleanersdallas.com
  skip_cleanup: true
  acl: public_read
  local_dir: dist
