language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id:
    secure: jq3bqQBxySnEzBN233NjDieaQ2hSwYPVv9GU6lG3nv1kyhwJTTkFatJmCltKzR98zBbh1/LRuA9797ry/K7SYuryTy2gcXaZ2A+3LmucwldlisVWMzTB67EJ81lm6t8PBon/QaMgsNQITz/20Ab2bFg6NCMO+y8wBtX2DoWzDg4sd0iwZTyjFimO+SdYFSfKbxmVaMVT85d8MNEK/z2S9IGMlDDODdpcz6iNLKxmLYZClCl02oNSfVRLubD/Tm9bKAI0Dhih5zccNdt0+JlDIfNOHB9FY0VgWlWrz9WWH86Rpb60fmIj2m39EhxBocpPRRFtP+5xGF2On9uwfF2V84XjeWnjKFK/rCPvhcFkgCsHs8ftEQ0AkbyRQ3ZXE+WXv/5UxtOUlS07yXF2ZbtAcGN0MtUfv7FwkVRiR6pjdMaps+yElTIYJRBqd3WTnbw+lM/kaKS3yAC6BqQOhnndPa3VbivjWt4kO9Q7zuhIWesGoSGOd1nojP4D/yJvl9Z1SWj2EHBWibFBNC/4/icCYn3fURYNF1Pd7vXAaKL8iru440cjeUk4xPAbXXVW5JxwdbOXMEABzR5+hnoIkbnhu7+oExczbtC7pKCx8W4rTnr5lhE9cqOgUSRbID3beaAC3rAf9A8szqCGj6SZ/1DgnLL3U47o+ZyIKGcLc/qgKi8=
  secret_access_key:
    secure: IH75U/q+1PdPTpMbcLF7WDZY2Gb2NJh4tqMCdtPbsN6YhJW6x4LdAe+cmmR1K3KyFXhLHJBA0lx/FfX6zDBs99yUq9cih1+C4YDdaDkA7c3CvJrjJz67uPk+iePtHwZFiOGB+5w5mgu/O9OwDv5rCU7c9AyqW5OpQs2xjodav94EMi2T58xDadM18cWWu4hfhDE8QDx/VwTJjcKnEKnRu0QMaacfzI5VFu7egquRoFSXGfHTynv72tfOJw+6rUGNXy+kouBcv4+/LrLOW7TmL81H0YGT2d+G1+19sJTevDNEHr7PTBmyyhMJC6g7zZUp4bNwsaF465ZQj+3BgCYlvYlZEs0eR7buPxnNBlAsO9eRH57NcgLKSkz4b4g/E1BSU3toFkhNgpld/Ov3YP2Aa/Yu3lDA0zzhQN+JQ5tib0qGuDqXt+12mx6Gfns28kBsyRcw8iCnRnh9z00wsoSkRhhENHFOaiL8INvSiyVWTOUuFQsvUZ1IlOVLm8/ZEsXbQ31VDNa9idCRK8gX+DiMHKz5DTt96remjCcjVCpWWmneYwQ5dG+/hN2Xjmjow84nXrIYknzASKWGQcsvWEOmAYi3dmF44Jj/IbVS5nhoele4CNxJBQJvz1voMUCbcTI83hYFvTVUK9TkbF3c6nGRX7uILV8SJ6ZnCEqHmZfSkfA=
  bucket: www.cadetcleaners.com
  skip_cleanup: true
  acl: public_read
  local_dir: dist
